name: ppaths
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- sparqlwrapper=1.8.5
- urllib3=1.25.10
- snakemake=5.25.0
- snakemake-minimal=5.25.0
- seaborn=0.11.0
- seaborn-base=0.11.0
- readline=8.0
- python=3.8.5
- numpy=1.19.1
- matplotlib=3.3.2
- matplotlib-base=3.3.2
- coloredlogs=14.0
- click=7.1.2
- altair=4.1.0